services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile
    image: webserver-web-dev:latest
    container_name: sys-web-1
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_PUBLIC_ENDPOINT: http://localhost:9000
      MINIO_BUCKET: webserver-files
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_UPLOAD_URL_EXPIRES: 300
      MINIO_DOWNLOAD_URL_EXPIRES: 300
      MINIO_MAX_FILENAME_LENGTH: 255
    depends_on:
      - mysql
      - redis
      - minio
    ports:
      - "8081:8080"  #external port 8081 mapped into internal container port 8080
    # command: >
    #   bash -lc "cmake -S . -B build &&
    #   cmake --build build &&
    #   ./build/bin/webserver 8080"
    stdin_open: true
    tty: true
  
  web2:
    build:
      context: .
      dockerfile: Dockerfile
    image: webserver-web-dev:latest
    container_name: sys-web-2
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_PUBLIC_ENDPOINT: http://localhost:9000
      MINIO_BUCKET: webserver-files
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_UPLOAD_URL_EXPIRES: 300
      MINIO_DOWNLOAD_URL_EXPIRES: 300
      MINIO_MAX_FILENAME_LENGTH: 255
    depends_on:
      - mysql
      - redis
      - minio
    ports:
      - "8082:8080"
    # command: >
    #   bash -lc "cmake -S . -B build &&
    #   cmake --build build &&
    #   ./build/bin/webserver 8080"
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    container_name: sys-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2
  
  mysql: #  Newly added database service
    image: mysql:8.0
    container_name: sys-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: webdb
      MYSQL_USER: webuser
      MYSQL_PASSWORD: webpass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  redis: # Newly added Redis service
    image: redis:7
    container_name: sys-redis
    ports: 
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: sys-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data


volumes:
  mysql_data:
  minio_data:
